name: discord_notify

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
     - name: discord ship
       env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
       uses: Ilshidur/action-discord@0.3
